# Generated by Django 3.0.6 on 2020-05-14 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificacaoDespesa',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'classificacao_despesa',
            },
        ),
        migrations.CreateModel(
            name='ClassificacaoReceita',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'classificacao_receita',
            },
        ),
        migrations.CreateModel(
            name='FuncaoDespesa',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'funcao_despesa',
            },
        ),
        migrations.CreateModel(
            name='FuncaoReceita',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=170)),
            ],
            options={
                'db_table': 'funcao_receita',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=70)),
                ('uf', models.CharField(max_length=2)),
                ('regiao', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'municipio',
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('ano', models.IntegerField()),
                ('valor', models.FloatField()),
                ('classificacao_receita_codigo', models.ForeignKey(db_column='classificacao_receita_codigo', on_delete=django.db.models.deletion.DO_NOTHING, to='api.ClassificacaoReceita')),
                ('funcao_receita_codigo', models.ForeignKey(db_column='funcao_receita_codigo', on_delete=django.db.models.deletion.DO_NOTHING, to='api.FuncaoReceita')),
                ('municipio_codigo', models.ForeignKey(db_column='municipio_codigo', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Municipio')),
            ],
            options={
                'db_table': 'receita',
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('ano', models.IntegerField()),
                ('valor', models.FloatField()),
                ('classificacao_despesa_codigo', models.ForeignKey(db_column='classificacao_despesa_codigo', on_delete=django.db.models.deletion.DO_NOTHING, to='api.ClassificacaoDespesa')),
                ('funcao_despesa_codigo', models.ForeignKey(db_column='funcao_despesa_codigo', on_delete=django.db.models.deletion.DO_NOTHING, to='api.FuncaoDespesa')),
                ('municipio_codigo', models.ForeignKey(db_column='municipio_codigo', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Municipio')),
            ],
            options={
                'db_table': 'despesa',
            },
        ),
    ]
